name: drupal9
recipe: drupal8
config:
  webroot: web
  php: '7.3'
  via: apache:2.4
  database: mysql:5.7
  xdebug: true
  config:
    database: drupal8
    username: drupal8
    password: drupal8
    host: database
    # for mysql
    port: 3306
services:
  appserver:
    build:
      - cd /app/web/ && composer install
    run:
      - cp /app/web/sites/default/default.settings.local.php /app/web/sites/default/settings.local.php
      - cd /app/web/ && drush sql-cli < ../db_dump/drupal.sql
      - cd /app/web/ && drush cr