preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: false
icon_default: true
icon_path: ''
_core:
  default_config_hash: bFamv6RfelnqY1J3G4wWSf02pL3GghIcwyKzZIoGniQ
