preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: vertical
icon_default: true
icon_path: ''
high_contrast_mode: false
third_party_settings:
  shortcut:
    module_link: true
_core:
  default_config_hash: CEHTCpo0zzrZOJNa9_M2R_HdYKrq3v1zlRVCf66hh7U
